### ISSUE TITLE
run under Windows

### ISSUE THREAD

**Issue by blr21560** [houqp/leptess#3] opened 2019-07-31 14:09 UTC
Hi,

I can't link under Windows. The linker search lept.lib.
Where can i find this library for windows ?
Thanks,

**Comment by greaka** [comment] 2019-07-31 14:28
have the same problem with the subsystem:

```
/mnt/c/Git/test/ocr > cargo run
   Compiling ocr v0.1.0 (/mnt/c/Git/test/ocr)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.1aqjxr5u0rdmlckl.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.1vdg48mrk1iskgcu.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.2hoot74qazfpxker.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.2qc7msxij3yzhzaj.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.2xht2ybnk1kt4hyl.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.3aitt1zkw0gytaur.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.3psd2pbazmg2b07e.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.44e3srg7ibfk4n2c.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.4792rjf1gjmr8fot.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.4qgmp5amdi87aeyu.rcgu.o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.e6e39wt3etvsmhw.rcgu.o" "-o" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2" "/mnt/c/Git/test/ocr/target/debug/deps/ocr-77fb0a037d890ce2.io0uraj5lxinwl0.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/mnt/c/Git/test/ocr/target/debug/deps" "-L" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/mnt/c/Git/test/ocr/target/debug/deps/libleptess-f8ca3d840c8dde6f.rlib" "-Wl,--start-group" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-9d237d17ebcf33da.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-c7aeb564d27a8408.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-8dcce133820ce36b.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-550595cd0e8605f6.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-616d93738996b317.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0bdc7ca6876dfe08.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-5f6229b11bb8dfe3.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-74acf7fdf307aa94.rlib" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-08e0675cab0aedce.rlib" "-Wl,--end-group" "/home/greaka/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ccce53ba085ea72e.rlib" "-Wl,-Bdynamic" "-llept" "-ltesseract" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: cannot find -llept
          /usr/bin/ld: cannot find -ltesseract
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `ocr`.

To learn more, run the command again with --verbose.
/mnt/c/Git/test/ocr >
```

**Comment by houqp** [comment] 2019-08-02 04:18
I am not familiar with windows, could you try the Linux subsystem?

**Comment by DuckerMan** [comment] 2020-01-09 14:17
Yeah, I need help with Windows too

**Comment by ccouzens** [comment] 2020-01-09 17:43
I'll give it a go and see what I can figure out this weekend.

Lept is the leptonica library http://www.leptonica.org/ https://github.com/DanBloomberg/leptonica

**Comment by ccouzens** [comment] 2020-01-10 21:39
These instructions are a work in progress. They don't actually get this running, but I feel like I made progress towards it.

Please install:

* [The Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)
* [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019)
* [Bindgen's requirements](https://rust-lang.github.io/rust-bindgen/requirements.html#windows)
* [vcpkg](https://github.com/Microsoft/vcpkg/blob/master/README.md)

Please run:

```Batchfile
vcpkg install leptonica tesseract
```

Set your `CPATH` for clang.

```Batchfile
# Modify to be your vcpkg installation directory
set CPATH=C:\Users\ccouz\Documents\git\github.com\Microsoft\vcpkg\installed\x64-windows\include
```

⚠️ But this doesn't make it link.
`Leptonica.lib` is installed at `C:\Users\ccouz\Documents\git\github.com\Microsoft\vcpkg\installed\x64-windows\lib\leptonica-1.78.0.lib` on my computer. I can't work out what environment variable to set to make it pick this up. Renaming it to `lept.lib` didn't seem to help.

**Comment by ccouzens** [comment] 2020-01-10 22:13
It's not a very satisfactory thing to do, but by copying

```
tesseract.lib (renamed from tesseract41.lib)
lept.lib (renamed from leptonica-1.78.0.lib)
```

from `C:\Users\ccouz\Documents\git\github.com\Microsoft\vcpkg\installed\x64-windows\lib` to the leptess directory, and with this minor patch

```patch
diff --git a/src/leptonica.rs b/src/leptonica.rs
index 1cea6eb7..0766ed88 100644
--- a/src/leptonica.rs
+++ b/src/leptonica.rs
@@ -103,7 +103,7 @@ impl Boxa {
         unsafe { (*self.raw).n as usize }
     }

-    pub fn get_box(&self, i: usize, flag: u32) -> Option<Box> {
+    pub fn get_box(&self, i: usize, flag: i32) -> Option<Box> {
         unsafe {
             let b = capi::boxaGetBox(self.raw, i as i32, flag as i32);
             if b.is_null() {
```

I was able to run `cargo test`.

I'd like the input of someone more familiar with building on Windows, so that we can make it far more seamless.

**Comment by DuckerMan** [comment] 2020-01-12 16:38
Anyway it's kind of progress

**Comment by ccouzens** [comment] 2020-01-12 21:53
I suspect the cause is that the 2 sys libraries used by leptess do not compile nicely on windows:

* https://github.com/ccouzens/leptonica-sys
* https://github.com/ccouzens/tesseract-sys

I'll try and update them with the suggestions from [this article](https://kornel.ski/rust-sys-crate). Maybe next weekend. It might mean some big changes to them (submoduling and compiling leptonica and tesseract for example).

**Comment by ccouzens** [comment] 2020-01-18 14:44
> I'll try and update them with the suggestions from this article. Maybe next weekend. It might mean some big changes to them (submoduling and compiling leptonica and tesseract for example).

This is currently beyond me, but (as always) I'll accept patches.

**Comment by rucoder** [comment] 2020-01-27 00:01
I figured it out for msvc toolchain! I'm building using VS 2019 community edition.

1. You should build from VS 2019 x64 native tools command prompt
2. set LIBCLANG_PATH=C:\<your path to LLVM distro>\bin
3. set INCLUDE=%INCLUDE%; <your path>\vcpkg\packages\leptonica_x64-windows\include
4. do 'cargo build' in your project directory

note, that vcpkg build x86 libs by default. If you need x64 libs (like in my case) 
set VCPKG_DEFAULT_TRIPLET=x64-windows

**Comment by rucoder** [comment] 2020-01-27 03:44
I'll try to come up with fixes for both *-sys crates. I'm going to use vcpkg crate for this purpose and conditionally use it on win platforms

**Comment by Shaddy** [comment] 2020-01-27 12:33
Thanks @rucoder for the update and @ccouzens for your work. Hope this leads into a usable workaround for Windows :). I'll try tonight these steps.

**Comment by DuckerMan** [comment] 2020-01-27 14:27
@rucoder What is LLVM ?

**Comment by ccouzens** [comment] 2020-01-27 22:07
> @rucoder What is LLVM ?

@DuckerMan it is a tool used to help building compilers. The Rust compiler uses it. It's also used by the compilers of many other languages. https://en.wikipedia.org/wiki/LLVM

The C compiler that uses LLVM is called Clang. I suspect Clang and LLVM are distributed together because C is a very important language.

I guess you're meant to download the Windows prebuilt binary from http://releases.llvm.org/download.html in order to follow @rucoder's instructions.

> set LIBCLANG_PATH=C:\'**your path to LLVM distro**'\bin

**Comment by ccouzens** [comment] 2020-01-27 22:11
> I'll try to come up with fixes for both *-sys crates. I'm going to use vcpkg crate for this purpose and conditionally use it on win platforms

Thank you @rucoder

**Comment by rucoder** [comment] 2020-01-28 07:50
Ok, the fixes for both *-sys crates are ready. This is my first time contributing to Rust libraries. Here is the question: I see that leptess depends on not the latest version of *sys crates. Should I just create PRS for the latest versions and then owners will integrate them back to earlier versions or... that is the process?

**Comment by ccouzens** [comment] 2020-01-28 08:23
> Ok, the fixes for both *-sys crates are ready. This is my first time contributing to Rust libraries. Here is the question: I see that leptess depends on not the latest version of *sys crates. Should I just create PRS for the latest versions and then owners will integrate them back to earlier versions or... that is the process?

First submit PRs for both *-sys crates.
Once those are merged and packaged, then any of us can update the dependencies of leptess.

Actually, I'm not sure we'll even have to update the dependencies of leptess, because [they're flexible](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio).

Leptess will currently try and install the newest version of leptonica-sys 0.3.x, and tesseract-sys 0.5.x.

**Comment by rucoder** [comment] 2020-01-28 09:43
I've submitted two PRs. Please note that following settings must be added to tasks.json in VS code if you use it

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cargo",
            "subcommand": "build",
            "problemMatcher": [
                "$rustc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            // These two environment variables MUST be defined for successfull build
            // if you need staically linked libraries then set
           // RUSTFLAGS=-Ctarget-feature=+crt-static instead of VCPKGRS_DYNAMIC
            "options": {
                "env": {
                    "LIBCLANG_PATH": "C:\\LLVM-OFF\\bin",
                    "VCPKGRS_DYNAMIC": "1"
                }
            }
        }
    ]
}
```

From vcpkg documentation

```
Note: You must set one of RUSTFLAGS=-Ctarget-feature=+crt-static or VCPKGRS_DYNAMIC=1 in your environment or the vcpkg-rs helper will not find any libraries. If VCPKGRS_DYNAMIC is set, cargo install will generate dynamically linked binaries, in which case you will have to arrange for dlls from your Vcpkg installation to be available in your path.
```
https://docs.rs/vcpkg/0.2.8/vcpkg/


I think READMY files should be updated as well

**Comment by ccouzens** [comment] 2020-02-02 23:05
Thanks to the excellent work @rucoder has done with `tesseract-sys` and `leptonica-sys`, I've been able to bring it all together and make a PR for running `leptess` on Windows.

Feel free to try it out and leave feedback if required https://github.com/houqp/leptess/pull/11

**Comment by rucoder** [comment] 2020-04-10 13:15
As I can see the work is not finished. The package version should be bumped to 0.8.2 and it should be re-released on craits.io. It is not enough to just bump leptonia-sys and teserract-sys craits version in cargo.toml

**Comment by ccouzens** [comment] 2020-04-10 13:28
Hi @rucoder , thanks for prompting me. I'll do that now.

**Comment by rucoder** [comment] 2020-04-10 14:11
> Hi @rucoder , thanks for prompting me. I'll do that now.

I'll be glad o be a first tester for this :)

**Comment by ccouzens** [comment] 2020-04-10 14:39
`leptess = "0.8.2"`

has been published. @rucoder let me know how you get on and thanks for your patience

**Comment by rucoder** [comment] 2020-04-10 15:23
I confirm that 0.8.2 builds and runs just fine on my PC. The issue can be closed I guess

**Closed** 2020-04-10 16:10 UTC
